=== ahmedasemsery/ITI-Fundamental-cources/XML Fundamentals/Lab1/Library.dtd
<!DOCTYPE library [
        <!ELEMENT library (libinfo)*>
        <!ELEMENT libinfo (location|description|librarian|books)*>
        <!ELEMENT location (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT librarian (age|phoneNumber|residentLocation|status)*>
        <!ATTLIST librarian
                id CDATA #REQUIRED
                name CDATA #REQUIRED
                gender CDATA #REQUIRED>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT phoneNumber (#PCDATA)>
        <!ELEMENT residentLocation (#PCDATA)>
        <!ELEMENT status (#PCDATA)>
        <!ELEMENT books (book)*>
        <!ELEMENT book (author|writer|title|preface|parts|category|price|publish_date|description)*>
        <!ATTLIST book
                id CDATA #REQUIRED>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT writer (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ATTLIST title
                lang CDATA #IMPLIED>
        <!ELEMENT preface (#PCDATA)>
        <!ELEMENT parts (part1)*>
        <!ELEMENT part1 (tilte|chapters)*>
        <!ATTLIST part1
                p CDATA #REQUIRED>
        <!ELEMENT tilte (#PCDATA)>
        <!ELEMENT chapters (chapter1)*>
        <!ELEMENT chapter1 (title|summary|sections)*>
        <!ELEMENT summary (#PCDATA)>
        <!ELEMENT sections (section1)*>
        <!ELEMENT section1 (pragraphs)*>
        <!ELEMENT pragraphs (pragraph1)*>
        <!ELEMENT pragraph1 (#PCDATA)>
        <!ELEMENT category (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT publish_date (#PCDATA)>
        <!ENTITY CS "Computer Science">
        <!ENTITY writer SYSTEM "writer.ent">
        ]>

=== ahmedasemsery/ITI-Fundamental-cources/XML Fundamentals/labs/Lab1/Library.xml
<?xml version="1.0" encoding = "UTF-8" standalone = "no"?>

<!DOCTYPE library SYSTEM "Library.dtd">

<library>
    <libinfo>
        <location>
            Cairo, Egypt
        </location>
        <description>
            Library for english software books
        </description>
        <librarian id = "123500" name = "Ahmed Asem" gender = "male">
            <age> 25 </age>
            <phoneNumber> 0 100 000 0000 </phoneNumber>
            <residentLocation> Minufia </residentLocation>
            <status> Single </status>

        </librarian>

        <books>

            <book id="101">
                <author> Kathy Sierra , Bert Bates </author>
                <writer> &writer; </writer>
                <ISBN> </ISBN>
                <title lang = "en"> Head First </title>
                <preface> </preface>
                <parts>
                    <part1 p = "part1">
                        <tilte> Introduction to java </tilte>
                        <chapters>
                            <chapter1>
                                <title> overview </title>
                                <summary> introducing java </summary>
                                <sections>
                                    <section1>
                                        <pragraphs>
                                            <pragraph1>

                                            </pragraph1>
                                        </pragraphs>
                                    </section1>
                                </sections>
                            </chapter1>

                            <![CDATA[
                                if(i < 5)
                                    System.out.println("Greater");
                            ]]>
                        </chapters>
                    </part1>
                </parts>
                <category> &CS; </category>
                <price>44.95</price>
                <publish_date>2000</publish_date>
                <description>
                    it has a very “user-friendly interface”:
                    you’ll get engaged from the first page till you finish it.
                </description>
            </book>

            <book id="102">
                <author> Barry Burd, PhD </author>
                <writer> &writer; </writer>
                <title lang = "en"> lang = "en"> Beginning Programming with Java For Dummies </title>
                <preface> </preface>
                <parts>
                    <part1 p = "part1">
                        <tilte> Introduction to java </tilte>
                        <chapters>
                            <chapter1>
                                <title> overview </title>
                                <summary> introducing java </summary>
                                <sections>
                                    <section1>
                                        <pragraphs>
                                            <pragraph1>

                                            </pragraph1>
                                        </pragraphs>
                                    </section1>
                                </sections>
                            </chapter1>
                        </chapters>
                    </part1>
                </parts>
                <category> &CS; </category>
                <price>100.50</price>
                <publish_date>2004</publish_date>
                <description>
                    very simple examples and lots of “how-tos”
                    if you have no idea of programming concepts.
                </description>
            </book>
        </books>
    </libinfo>
</library>
